// import { Metadata } from "next";
import Header from "../../components/Header";
// export const metadata: Metadata = {
//   title: {
//     default: "Homepage",
//     template: "%s | Pintastic",
//   },
//   // description: "Generated by create next app",
// };
export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section>
      <Header />
      {children}
    </section>
  );
}
